tasks:
  - init: git remote set-url origin git@github.com:IndumathiKrish/IndumathiKrish-Project0.git && sed "s/\r$//" commit-command.sh | bash
vscode:
 extensions:
   - redhat.java
   - vscjava.vscode-java-debug
   - revaturePro.revature-labs